### ISSUE TITLE
'add-highlighter' No such highlighter factory '/'

### ISSUE THREAD

**Issue by janwirth** [atomrc/kakoune-typescript#1]
What is the best way to fetch the dependencies required by this formidable piece of software?

```
*** This is the debug buffer, where debug info will be written ***
Dependency unmet: gocode, please install it to use go-tools
Dependency unmet: goimports, please install it to use go-tools
Dependency unmet: gogetdoc, please install it to use go-tools
Dependency unmet: jq, please install it to use go-tools
~/dotfiles/typescript.kak:11:176: 'add-highlighter' No such highlighter factory '/'
/Users/wirthjan/.config/kak/kakrc:39:1454: 'source' 11:176: 'add-highlighter' No such highlighter factory '/'
/usr/local/Cellar/kakoune/HEAD-35d68d2/share/kak/kakrc:86:18139: 'source' 39:1454: 'source' 11:176: 'add-highlighter' No such highlighter factory '/'
error while parsing kakrc:
    1:1: 'source' 86:18139: 'source' 39:1454: 'source' 11:176: 'add-highlighter' No such highlighter factory '/'
```

**Comment by atomrc** [comment]
Hello kind sir, and thanks for reporting this :)

So, the issue is actually not with `kakoune-typescript` but within `kakoune` itself.
You need to install those dependencies if you want code-completion, formatting on save and a bunch of other stuffs.
Have a look at this file for more information https://github.com/mawww/kakoune/blob/master/rc/extra/go-tools.kak

**Comment by janwirth** [comment]
Hey Atom,

I still don't quite see why this required for kakoune-ts nor a description on how to obtain the dependencies. I'm manually fetching every single dep now which is not very comfortable :(

**Comment by atomrc** [comment]
This is not required at all for `kakoune-typescript`! It just enables other functionalities for Kakoune.

Looking closely at the log you provided, there is a weird error with the highlighter though. Not sure why there is this error.

**Comment by janwirth** [comment]
Oh well - sorry. I thought the dependencies were part of the typescript.kak :(

I fetched the script directly using curl. Will see what I can do to fix the highligther factory error.

**Comment by janwirth** [comment]
Okey - so the highlighter factory `/` is not found. If I put `/typescript` there, it does not crash, but also does not work either. I'm not familiar enough with kakoune yet unfortunately.

**Comment by atomrc** [comment]
I am currently digging into kakoune to see if something changed since I wrote the plugin. 

There is a commit related to highlight groups and `/` character. Maybe this is relevant... Not sure yet
https://github.com/mawww/kakoune/commit/39e63cf518074564992614c117d9e40a9011c425

**Comment by atomrc** [comment]
It seems the file I inspired from initially has changed a bit. So I might need to fix those highlighters declaration on my end.
https://github.com/mawww/kakoune/blob/master/rc/base/javascript.kak

Again thanks for the report and sorry for the inconvenience

**Comment by janwirth** [comment]
All good.

**Comment by atomrc** [comment]
Yeah, there were some breaking changes regarding highlighters. 
https://github.com/mawww/kakoune/issues/2045#issuecomment-388781731
Will try to fix this soon :+1:

**Comment by atomrc** [comment]
It is now fixed. Thanks again for the report.
Maybe that's my cue to restart using Kakoune again :D

**Comment by janwirth** [comment]
Yess! Which editor are you using atm?

**Comment by atomrc** [comment]
Neovim.
